version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "3000:80"
    volumes:
      - ./node_modules:/app/node_modules
    env_file:
      - ./apps/haust-dex/.env.production
