version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env 
